import 'dart:core';

import '../../features/booking/models/property/availability.dart';
import '../../features/booking/models/property/listing_category.dart';
import '../../features/booking/models/property/listing_model.dart';
import '../../features/booking/models/property/owner.dart';
import '../../features/booking/models/property/property_section.dart';
import '../../features/booking/models/property/property_type.dart';
import '../../features/booking/models/property/room.dart';

class TTestListings {
  static List<Room> listing1Rooms = [
    Room(
      roomId: "1",
      listingId: "1",
      roomDescription: "Single Saver",
      bedAndBashBoardPictures: [
        "assets/images/rooms/pexels-heyho-6588577.jpg",
        "assets/images/rooms/pexels-andrew-3201763.jpg",
      ],
      bathAndToilet: [
        "assets/images/rooms/bath1.jpg",
        "assets/images/rooms/bath2.jpg",
        "assets/images/rooms/bath3.jpg",
      ],
      otherRoomPictures: [
        "assets/images/rooms/pexels-heyho-6588572.jpg",
        "assets/images/rooms/pexels-heyho-6588577.jpg",
      ],
      price: 3500.0,
      isOnPromotion: true,
      bedCount: 2,
      guestCount: 2,
      bathCount: 1,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: .25,
      availability: Availability.Confirm,
    ),
    Room(
      roomId: "2",
      listingId: "1",
      roomDescription: "Executive Room",
      bedAndBashBoardPictures: ["assets/images/rooms/pexels-heyho-6782567.jpg"],
      bathAndToilet: [
        "assets/images/rooms/pexels-heyho-6782567 (1).jpg",
        "assets/images/rooms/pexels-heyho-6899347.jpg",
        "assets/images/rooms/pexels-heyho-6899448.jpg",
      ],
      otherRoomPictures: [
        "assets/images/rooms/pexels-jimmy-teoh-294331-2411759.jpg",
        "assets/images/rooms/pexels-jonathanborba-3144580.jpg",
      ],
      price: 5500.0,
      isOnPromotion: false,
      bedCount: 2,
      guestCount: 2,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: 0.0,
      availability: Availability.Confirm,
      bathCount: 2,
    ),
    Room(
      roomId: "1",
      listingId: "1",
      roomDescription: "Single Saver",
      bedAndBashBoardPictures: [
        "assets/images/rooms/pexels-heyho-6588577.jpg",
        "assets/images/rooms/pexels-andrew-3201763.jpg",
      ],
      bathAndToilet: [
        "assets/images/rooms/bath1.jpg",
        "assets/images/rooms/bath2.jpg",
        "assets/images/rooms/bath3.jpg",
      ],
      otherRoomPictures: [
        "assets/images/rooms/pexels-heyho-6588572.jpg",
        "assets/images/rooms/pexels-heyho-6588577.jpg",
      ],
      price: 3500.0,
      isOnPromotion: true,
      bedCount: 2,
      guestCount: 2,
      bathCount: 1,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: .25,
      availability: Availability.Confirm,
    ),
    Room(
      roomId: "2",
      listingId: "1",
      roomDescription: "Executive Room",
      bedAndBashBoardPictures: ["assets/images/rooms/pexels-heyho-6782567.jpg"],
      bathAndToilet: [
        "assets/images/rooms/pexels-heyho-6782567 (1).jpg",
        "assets/images/rooms/pexels-heyho-6899347.jpg",
        "assets/images/rooms/pexels-heyho-6899448.jpg",
      ],
      otherRoomPictures: [
        "assets/images/rooms/pexels-jimmy-teoh-294331-2411759.jpg",
        "assets/images/rooms/pexels-jonathanborba-3144580.jpg",
      ],
      price: 5500.0,
      isOnPromotion: false,
      bedCount: 2,
      guestCount: 2,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: 0.0,
      availability: Availability.Confirm,
      bathCount: 2,
    ),
  ];
  static List<Room> listing2Rooms = [
    Room(
      roomId: "3",
      listingId: "2",
      roomDescription: "Guest Bedroom",
      bedAndBashBoardPictures: [
        "assets/images/rooms/pexels-julieaagaard-5044289.jpg",
        "assets/images/rooms/pexels-jvdm-1457842.jpg",
        "assets/images/rooms/pexels-kamenczak-775219.jpg",
      ],
      bathAndToilet: [
        "assets/images/rooms/pexels-lamiko-3754595.jpg",
        "assets/images/rooms/pexels-naimbic-2029698.jpg",
        "assets/images/rooms/pexels-orlovamaria-4946758.jpg",
      ],
      otherRoomPictures: [
        "assets/images/products/acer_laptop_2.png",
        "hassets/images/products/acer_laptop_2.png",
      ],
      price: 850.0,
      isOnPromotion: true,
      bedCount: 2,
      guestCount: 2,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: .15,
      availability: Availability.Confirm,
      bathCount: 2,
    ),
    Room(
      roomId: "3",
      listingId: "2",
      roomDescription: "Master Bedrooom",
      bedAndBashBoardPictures: [
        "assets/images/rooms/pexels-pixabay-271618.jpg",
        "assets/images/rooms/pexels-pixabay-271619.jpg",
        "assets/images/rooms/pexels-pixabay-271624.jpg",
      ],
      bathAndToilet: [
        "assets/images/rooms/pexels-pixabay-271643.jpg",
        "assets/images/rooms/pexels-pixabay-271618.jpg",
        "assets/images/rooms/pexels-andrew-3201763.jpg",
      ],
      otherRoomPictures: [
        "assets/images/rooms/pexels-enginakyurt-1579253.jpg",
        "assets/images/rooms/pexels-fotoaibe-1743229.jpg",
        "assets/images/rooms/pexels-heyho-6538895.jpg",
      ],
      price: 1400.0,
      isOnPromotion: false,
      bedCount: 2,
      guestCount: 2,
      bathCount: 2,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: 0.0,
      availability: Availability.Confirm,
    ),
  ];
  static List<Room> listing3Rooms = [
    Room(
      roomId: "3",
      listingId: "2",
      roomDescription: "Guest Bedroom",
      bedAndBashBoardPictures: [
        "assets/images/rooms/pexels-heyho-6588572.jpg",
        "assets/images/rooms/pexels-heyho-6588577.jpg",
        "assets/images/rooms/pexels-heyho-6782567.jpg",
      ],
      bathAndToilet: [
        "assets/images/rooms/pexels-heyho-6782567 (1).jpg",
        "assets/images/rooms/pexels-heyho-6899347.jpg",
        "assets/images/rooms/pexels-heyho-6899448.jpg",
      ],
      otherRoomPictures: [
        "assets/images/rooms/pexels-jimmy-teoh-294331-2411759.jpg",
        "assets/images/rooms/pexels-jonathanborba-3144580.jpg",
      ],
      price: 850.0,
      isOnPromotion: true,
      bedCount: 2,
      guestCount: 2,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: .15,
      availability: Availability.Confirm,
      bathCount: 2,
    ),
    Room(
      roomId: "3",
      listingId: "2",
      roomDescription: "Master Bedrooom",
      bedAndBashBoardPictures: [
        "assets/images/rooms/pexels-julieaagaard-5044289.jpg",
        "assets/images/rooms/pexels-jvdm-1457842.jpg",
        "assets/images/rooms/pexels-kamenczak-775219.jpg",
      ],
      bathAndToilet: [
        "assets/images/rooms/pexels-kamenczak-775219.jpg",
        "assets/images/rooms/pexels-naimbic-2029698.jpg",
        "assets/images/rooms/pexels-orlovamaria-4946758.jpg",
      ],
      otherRoomPictures: [
        "assets/images/rooms/pexels-pixabay-271618.jpg",
        "assets/images/rooms/pexels-pixabay-271619.jpg",
        "assets/images/rooms/pexels-pixabay-271624.jpg",
      ],
      price: 400.0,
      isOnPromotion: false,
      bedCount: 2,
      guestCount: 2,
      bathCount: 2,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: 0.0,
      availability: Availability.Confirm,
    ),
  ];
  static List<Room> listing4Rooms = [
    Room(
      roomId: "3",
      listingId: "2",
      roomDescription: "Guest Bedroom",
      bedAndBashBoardPictures: [
        "assets/images/rooms/pexels-pixabay-271643.jpg",
        "assets/images/rooms/pexels-pixabay-271618.jpg",
        "assets/images/rooms/pexels-andrew-3201763.jpg",
      ],
      bathAndToilet: [
        "assets/images/rooms/pexels-enginakyurt-1579253.jpg",
        "assets/images/rooms/pexels-fotoaibe-1743229.jpg",
        "assets/images/rooms/pexels-heyho-6538895.jpg",
      ],
      otherRoomPictures: [
        "assets/images/rooms/pexels-heyho-6588572.jpg",
        "assets/images/rooms/pexels-heyho-6588577.jpg",
      ],
      price: 1850.0,
      isOnPromotion: true,
      bedCount: 2,
      guestCount: 2,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: .15,
      availability: Availability.Confirm,
      bathCount: 2,
    ),
    Room(
      roomId: "3",
      listingId: "2",
      roomDescription: "Master Bedrooom",
      bedAndBashBoardPictures: [
        "assets/images/rooms/pexels-heyho-6782567.jpg",
        "assets/images/rooms/pexels-heyho-6782567 (1).jpg",
        "assets/images/rooms/pexels-heyho-6899347.jpg",
      ],
      bathAndToilet: [
        "assets/images/rooms/pexels-heyho-6899448.jpg",
        "assets/images/rooms/pexels-jimmy-teoh-294331-2411759.jpg",
        "assets/images/rooms/pexels-jonathanborba-3144580.jpg",
      ],
      otherRoomPictures: [
        "assets/images/rooms/pexels-julieaagaard-5044289.jpg",
        "assets/images/rooms/pexels-jvdm-1457842.jpg",
        "assets/images/rooms/pexels-kamenczak-775219.jpg",
      ],
      price: 1100.0,
      isOnPromotion: false,
      bedCount: 2,
      guestCount: 2,
      bathCount: 2,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: 0.0,
      availability: Availability.Confirm,
    ),
  ];
  static List<Room> listing5Rooms = [
    Room(
      roomId: "3",
      listingId: "2",
      roomDescription: "Guest Bedroom",
      bedAndBashBoardPictures: [
        "assets/images/rooms/pexels-pixabay-271618.jpg",
        "assets/images/rooms/pexels-orlovamaria-4946758.jpg"
            "assets/images/rooms/pexels-pixabay-271618.jpg",
      ],
      bathAndToilet: [
        "assets/images/rooms/pexels-lamiko-3754595.jpg",
        "assets/images/rooms/pexels-naimbic-2029698.jpg",
        "assets/images/rooms/pexels-orlovamaria-4946758.jpg",
      ],
      otherRoomPictures: [
        "assets/images/rooms/pexels-pixabay-271618.jpg",
        "assets/images/rooms/pexels-pixabay-271619.jpg",
      ],
      price: 950.0,
      isOnPromotion: true,
      bedCount: 2,
      guestCount: 2,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: .15,
      availability: Availability.Confirm,
      bathCount: 2,
    ),
    Room(
      roomId: "3",
      listingId: "2",
      roomDescription: "Master Bedrooom",
      bedAndBashBoardPictures: [
        "assets/images/rooms/pexels-pixabay-271624.jpg",
        "assets/images/rooms/pexels-pixabay-271643.jpg",
        "assets/images/rooms/pexels-pixabay-271618.jpg",
      ],
      bathAndToilet: [
        "assets/images/rooms/pexels-andrew-3201763.jpg",
        "assets/images/rooms/pexels-enginakyurt-1579253.jpg",
        "assets/images/rooms/pexels-fotoaibe-1743229.jpg",
      ],
      otherRoomPictures: [
        "assets/images/rooms/pexels-heyho-6538895.jpg",
        "assets/images/rooms/pexels-heyho-6588572.jpg",
        "assets/images/rooms/pexels-heyho-6588577.jpg",
      ],
      price: 670.0,
      isOnPromotion: false,
      bedCount: 2,
      guestCount: 2,
      bathCount: 2,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: 0.0,
      availability: Availability.Confirm,
    ),
  ];
  static List<Room> listing6Rooms = [
    Room(
      roomId: "3",
      listingId: "2",
      roomDescription: "Guest Bedroom",
      bedAndBashBoardPictures: [
        "assets/images/rooms/pexels-heyho-6782567.jpg",
        "assets/images/rooms/pexels-heyho-6782567 (1).jpg",
        "assets/images/rooms/pexels-heyho-6899347.jpg",
      ],
      bathAndToilet: [
        "assets/images/rooms/pexels-heyho-6899448.jpg",
        "assets/images/rooms/pexels-jimmy-teoh-294331-2411759.jpg",
        "assets/images/rooms/pexels-jonathanborba-3144580.jpg",
      ],
      otherRoomPictures: [
        "assets/images/rooms/pexels-julieaagaard-5044289.jpg",
        "assets/images/rooms/pexels-jvdm-1457842.jpg",
      ],
      price: 850.0,
      isOnPromotion: true,
      bedCount: 2,
      guestCount: 2,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: .15,
      availability: Availability.Confirm,
      bathCount: 2,
    ),
    Room(
      roomId: "3",
      listingId: "2",
      roomDescription: "Master Bedrooom",
      bedAndBashBoardPictures: [
        "assets/images/rooms/pexels-kamenczak-775219.jpg",
        "assets/images/rooms/pexels-lamiko-3754595.jpg",
        "assets/images/rooms/pexels-naimbic-2029698.jpg",
      ],
      bathAndToilet: [
        "assets/images/rooms/pexels-orlovamaria-4946758.jpg",
        "assets/images/rooms/pexels-pixabay-271618.jpg",
        "assets/images/rooms/pexels-pixabay-271619.jpg",
      ],
      otherRoomPictures: [
        "assets/images/rooms/pexels-pixabay-271624.jpg",
        "assets/images/rooms/pexels-pixabay-271643.jpg",
        "assets/images/rooms/pexels-pixabay-271618.jpg",
      ],
      price: 1400.0,
      isOnPromotion: false,
      bedCount: 2,
      guestCount: 2,
      bathCount: 2,
      hasTv: true,
      hasAirConditioning: true,
      petAllowed: false,
      smokingAllowed: false,
      promotionDiscount: 0.0,
      availability: Availability.Confirm,
    ),
  ];

  static List<ListingModel> properties = [
    ListingModel(
      listingId: "1",
      // Name & Own Info
      propertyName: "Protea Hotel",
      listingCategory: ListingCategory.MultiHost,
      hostName: "",
      summary: 'backgroundColor',
      description:
          """We are taking extra care to disinfect your space due to COVID-19.
What guests say about 58 On Hume…
Amazing stay! A hidden gem, an oasis in a city.
Great accommodation, welcoming atmosphere, terrific food.
Location is the best in Joburg and close to lots of restaurants.
The service and hospitality exceeds most hotels by far and rooms are exactly as""",
      userId: "bsCY8sl14rZ3ujiOsEipdVF2gdu1",
      dateTimePublished: DateTime.now(),
      businessType: Owner.Business,
      propertyImages: [
        "assets/images/rooms/pexels-heyho-6588572.jpg",
        "assets/images/rooms/pexels-andrew-3201763.jpg",
        "assets/images/rooms/pexels-enginakyurt-1579253.jpg",
      ],
      area: "Cairo Road",
      city: "Lusaka",
      latitude: -15.4177,
      longitude: 28.3447,
      rating: 4.6,
      startingRoomPrice: 2500.0,
      isApproved: true,
      // List of Rooms available to book
      // Amenities And Rules
      hasWifi: true,
      hasKitchen: false,
      hasSwimmingPool: false,
      hasCarPark: false,
      hasGym: false,
      cancellationPercent: 0.0,
      rooms: listing1Rooms,
      highestDiscount: .10,
      distanceFromUser: 234,
      numberOfReviews: 9,
      propertyType: PropertyType.Apartment, listOfAmenities: [],
    ),
    ListingModel(
      listingId: "2",
      // Name & Own Info
      propertyName: "Ajay's Home",
      listingCategory: ListingCategory.MultiHost,
      propertyType: PropertyType.Apartment,
      hostName: "Ajay",
      summary: "sdfs",
      description:
          "My name is Ajay. I own this lovely Holiday home in Livingstone",
      userId: "bsCY8sl14rZ3ujiOsEipdVF2gdu1",
      dateTimePublished: DateTime.now(),
      businessType: Owner.Person,
      propertyImages: [
        "assets/images/rooms/pexels-fotoaibe-1743229.jpg",
        "assets/images/rooms/pexels-heyho-6538895.jpg",
        "assets/images/rooms/pexels-heyho-6588572.jpg",
      ],
      area: "Livingstone Victoria Falls",
      city: "Livingstone",
      latitude: -15.4177,
      longitude: 28.3447,
      rating: 4.9,
      startingRoomPrice: 850.0,
      isApproved: true,
      // List of Rooms available to book

      // Amenities And Rules
      hasWifi: true,
      hasKitchen: false,
      hasSwimmingPool: false,
      hasCarPark: false,
      hasGym: false,
      cancellationPercent: 0.0,
      rooms: listing2Rooms,
      highestDiscount: 0.2,
      distanceFromUser: 43,
      numberOfReviews: 8, listOfAmenities: [],
    ),
    ListingModel(
      listingId: "3",
      // Name & Own Info
      propertyName: "Villa Mbandi",
      listingCategory: ListingCategory.MultiHost,
      propertyType: PropertyType.Apartment,
      hostName: "",
      summary: "sddsf",
      description: "The heart of Serenje town",
      userId: "bsCY8sl14rZ3ujiOsEipdVF2gdu1",
      dateTimePublished: DateTime.now(),
      businessType: Owner.Business,
      propertyImages: [
        "assets/images/rooms/pexels-heyho-6588577.jpg",
        "assets/images/rooms/pexels-heyho-6782567.jpg",
        "assets/images/rooms/pexels-heyho-6782567 (1).jpg",
      ],
      area: "Town Centre",
      city: "Serenje",
      latitude: -15.4177,
      longitude: 28.3447,
      rating: 3.4,
      startingRoomPrice: 450.0,
      isApproved: true,
      // List of Rooms available to book
      // Amenities And Rules
      hasWifi: true,
      hasKitchen: false,
      hasSwimmingPool: false,
      hasCarPark: false,
      hasGym: false,
      cancellationPercent: 0.0,
      rooms: listing3Rooms,
      highestDiscount: 0.0,
      distanceFromUser: 234,
      numberOfReviews: 9, listOfAmenities: [],
    ),
    ListingModel(
      summary: "sf",
      listingId: "4",
      // Name & Own Info
      propertyName: "James's Home",
      listingCategory: ListingCategory.MultiHost,
      propertyType: PropertyType.Apartment,
      hostName: "James",
      description:
          "My name is Ajay. I own this lovely Holiday home in Livingstone",
      userId: "bsCY8sl14rZ3ujiOsEipdVF2gdu1",
      dateTimePublished: DateTime.now(),
      businessType: Owner.Person,
      propertyImages: [
        "assets/images/rooms/pexels-jimmy-teoh-294331-2411759.jpg",
      ],
      area: "Hillcrest Area",
      city: "Livingstone",
      latitude: -15.4177,
      longitude: 28.3447,
      rating: 4.3,
      startingRoomPrice: 850.0,
      isApproved: true,
      // List of Rooms available to book

      // Amenities And Rules
      hasWifi: true,
      hasKitchen: false,
      hasSwimmingPool: false,
      hasCarPark: false,
      hasGym: false,
      cancellationPercent: 0.0,
      rooms: listing4Rooms,
      highestDiscount: 0.4,
      distanceFromUser: 43,
      numberOfReviews: 8, listOfAmenities: [],
    ),
    ListingModel(
      listingId: "5",
      // Name & Own Info
      propertyName: "Mika Hotel",
      listingCategory: ListingCategory.MultiHost,
      propertyType: PropertyType.Apartment,
      hostName: "",
      description: "Lovely city views await your arrival",
      summary: "sddsfs",
      userId: "bsCY8sl14rZ3ujiOsEipdVF2gdu1",
      dateTimePublished: DateTime.now(),
      businessType: Owner.Business,
      propertyImages: [
        "assets/images/rooms/pexels-jonathanborba-3144580.jpg",
        "assets/images/rooms/pexels-julieaagaard-5044289.jpg",
        "assets/images/rooms/pexels-jvdm-1457842.jpg",
      ],
      area: "Kabulonga",
      city: "Lusaka",
      latitude: -15.4177,
      longitude: 28.3447,
      rating: 4.9,
      startingRoomPrice: 1500.0,
      isApproved: true,
      // List of Rooms available to book
      // Amenities And Rules
      hasWifi: true,
      hasKitchen: false,
      hasSwimmingPool: false,
      hasCarPark: false,
      hasGym: false,
      cancellationPercent: 0.0,
      rooms: listing5Rooms,
      highestDiscount: 0.0,
      distanceFromUser: 234,
      numberOfReviews: 9, listOfAmenities: [],
    ),
    ListingModel(
      listingId: "5",
      // Name & Own Info
      propertyName: "Mika Hotel",
      listingCategory: ListingCategory.MultiHost,
      propertyType: PropertyType.Apartment,
      hostName: "",
      summary: "sdsdfs",
      description: "Lovely city views await your arrival",
      userId: "bsCY8sl14rZ3ujiOsEipdVF2gdu1",
      dateTimePublished: DateTime.now(),
      businessType: Owner.Business,
      propertyImages: [
        "assets/images/rooms/pexels-jonathanborba-3144580.jpg",
        "assets/images/rooms/pexels-julieaagaard-5044289.jpg",
        "assets/images/rooms/pexels-jvdm-1457842.jpg",
      ],
      area: "Kabulonga",
      city: "Lusaka",
      latitude: -15.4177,
      longitude: 28.3447,
      rating: 4.9,
      startingRoomPrice: 1500.0,
      isApproved: true,
      // List of Rooms available to book
      // Amenities And Rules
      hasWifi: true,
      hasKitchen: false,
      hasSwimmingPool: false,
      hasCarPark: false,
      hasGym: false,
      cancellationPercent: 0.0,
      rooms: listing5Rooms,
      highestDiscount: 0.0,
      distanceFromUser: 234,
      numberOfReviews: 9, listOfAmenities: [],
    ),
    ListingModel(
      listingId: "4",
      // Name & Own Info
      propertyName: "James's Home",
      listingCategory: ListingCategory.MultiHost,
      propertyType: PropertyType.Apartment,
      hostName: "James",
      summary: "sdfsdf",
      description:
          "My name is Ajay. I own this lovely Holiday home in Livingstone",
      userId: "bsCY8sl14rZ3ujiOsEipdVF2gdu1",
      dateTimePublished: DateTime.now(),
      businessType: Owner.Person,
      propertyImages: [
        "assets/images/rooms/pexels-jimmy-teoh-294331-2411759.jpg",
      ],
      area: "Hillcrest Area",
      city: "Livingstone",
      latitude: -15.4177,
      longitude: 28.3447,
      rating: 4.3,
      startingRoomPrice: 850.0,
      isApproved: true,
      // List of Rooms available to book

      // Amenities And Rules
      hasWifi: true,
      hasKitchen: false,
      hasSwimmingPool: false,
      hasCarPark: false,
      hasGym: false,
      cancellationPercent: 0.0,
      rooms: listing4Rooms,
      highestDiscount: 0.4,
      distanceFromUser: 43,
      numberOfReviews: 8, listOfAmenities: [],
    ),
    ListingModel(
      listingId: "4",
      // Name & Own Info
      propertyName: "James's Home",
      listingCategory: ListingCategory.MultiHost,
      propertyType: PropertyType.Apartment,
      hostName: "James",
      summary: "Sdfsdf",
      description:
          "My name is Ajay. I own this lovely Holiday home in Livingstone",
      userId: "bsCY8sl14rZ3ujiOsEipdVF2gdu1",
      dateTimePublished: DateTime.now(),
      businessType: Owner.Person,
      propertyImages: [
        "assets/images/rooms/pexels-jimmy-teoh-294331-2411759.jpg",
      ],
      area: "Hillcrest Area",
      city: "Livingstone",
      latitude: -15.4177,
      longitude: 28.3447,
      rating: 4.3,
      startingRoomPrice: 850.0,
      isApproved: true,
      // List of Rooms available to book

      // Amenities And Rules
      hasWifi: true,
      hasKitchen: false,
      hasSwimmingPool: false,
      hasCarPark: false,
      hasGym: false,
      cancellationPercent: 0.0,
      rooms: listing4Rooms,
      highestDiscount: 0.4,
      distanceFromUser: 43,
      numberOfReviews: 8, listOfAmenities: [],
    ),
    ListingModel(
      listingId: "3",
      // Name & Own Info
      propertyName: "Villa Mbandi",
      listingCategory: ListingCategory.MultiHost,
      propertyType: PropertyType.Apartment,
      hostName: "",
      summary: "Sdfsdf",
      description: "The heart of Serenje town",
      userId: "bsCY8sl14rZ3ujiOsEipdVF2gdu1",
      dateTimePublished: DateTime.now(),
      businessType: Owner.Business,
      propertyImages: [
        "assets/images/rooms/pexels-heyho-6588577.jpg",
        "assets/images/rooms/pexels-heyho-6782567.jpg",
        "assets/images/rooms/pexels-heyho-6782567 (1).jpg",
      ],
      area: "Town Centre",
      city: "Serenje",
      latitude: -15.4177,
      longitude: 28.3447,
      rating: 3.4,
      startingRoomPrice: 450.0,
      isApproved: true,
      // List of Rooms available to book
      // Amenities And Rules
      hasWifi: true,
      hasKitchen: false,
      hasSwimmingPool: false,
      hasCarPark: false,
      hasGym: false,
      cancellationPercent: 0.0,
      rooms: listing3Rooms,
      highestDiscount: 0.0,
      distanceFromUser: 234,
      numberOfReviews: 9, listOfAmenities: [],
    ),
    ListingModel(
      listingId: "3",
      // Name & Own Info
      propertyName: "Villa Mbandi",
      listingCategory: ListingCategory.MultiHost,
      propertyType: PropertyType.Apartment,
      hostName: "",
      description: "The heart of Serenje town",
      summary: "SDfsdf",
      userId: "bsCY8sl14rZ3ujiOsEipdVF2gdu1",
      dateTimePublished: DateTime.now(),
      businessType: Owner.Business,
      propertyImages: [
        "assets/images/rooms/pexels-heyho-6588577.jpg",
        "assets/images/rooms/pexels-heyho-6782567.jpg",
        "assets/images/rooms/pexels-heyho-6782567 (1).jpg",
      ],
      area: "Town Centre",
      city: "Serenje",
      latitude: -15.4177,
      longitude: 28.3447,
      rating: 3.4,
      startingRoomPrice: 450.0,
      isApproved: true,
      // List of Rooms available to book
      // Amenities And Rules
      hasWifi: true,
      hasKitchen: false,
      hasSwimmingPool: false,
      hasCarPark: false,
      hasGym: false,
      cancellationPercent: 0.0,
      rooms: listing3Rooms,
      highestDiscount: 0.0,
      distanceFromUser: 234,
      numberOfReviews: 9, listOfAmenities: [],
    ),
    ListingModel(
      listingId: "2",
      // Name & Own Info
      propertyName: "Ajay's Home",
      listingCategory: ListingCategory.MultiHost,
      propertyType: PropertyType.Apartment,
      hostName: "Ajay",
      summary: "SDFSDf",
      description:
          "My name is Ajay. I own this lovely Holiday home in Livingstone",
      userId: "bsCY8sl14rZ3ujiOsEipdVF2gdu1",
      dateTimePublished: DateTime.now(),
      businessType: Owner.Person,
      propertyImages: [
        "assets/images/rooms/pexels-fotoaibe-1743229.jpg",
        "assets/images/rooms/pexels-heyho-6538895.jpg",
        "assets/images/rooms/pexels-heyho-6588572.jpg",
      ],
      area: "Livingstone Victoria Falls",
      city: "Livingstone",
      latitude: -15.4177,
      longitude: 28.3447,
      rating: 4.9,
      startingRoomPrice: 850.0,
      isApproved: true,
      // List of Rooms available to book

      // Amenities And Rules
      hasWifi: true,
      hasKitchen: false,
      hasSwimmingPool: false,
      hasCarPark: false,
      hasGym: false,
      cancellationPercent: 0.0,
      rooms: listing2Rooms,
      highestDiscount: 0.2,
      distanceFromUser: 43,
      numberOfReviews: 8, listOfAmenities: [],
    ),
    ListingModel(
      listingId: "2",
      // Name & Own Info
      propertyName: "Ajay's Home",
      listingCategory: ListingCategory.MultiHost,
      propertyType: PropertyType.Apartment,
      hostName: "Ajay",
      summary: "DSFsdf",
      description:
          "My name is Ajay. I own this lovely Holiday home in Livingstone",
      userId: "bsCY8sl14rZ3ujiOsEipdVF2gdu1",
      dateTimePublished: DateTime.now(),
      businessType: Owner.Person,
      propertyImages: [
        "assets/images/rooms/pexels-fotoaibe-1743229.jpg",
        "assets/images/rooms/pexels-heyho-6538895.jpg",
        "assets/images/rooms/pexels-heyho-6588572.jpg",
      ],
      area: "Livingstone Victoria Falls",
      city: "Livingstone",
      latitude: -15.4177,
      longitude: 28.3447,
      rating: 4.9,
      startingRoomPrice: 850.0,
      isApproved: true,
      // List of Rooms available to book

      // Amenities And Rules
      hasWifi: true,
      hasKitchen: false,
      hasSwimmingPool: false,
      hasCarPark: false,
      hasGym: false,
      cancellationPercent: 0.0,
      rooms: listing2Rooms,
      highestDiscount: 0.2,
      distanceFromUser: 43,
      numberOfReviews: 8, listOfAmenities: [],
    ),
  ];
}

class TTestPropertySections {
  static List<PropertySection> propertySections = [
    PropertySection(
      sectionName: "Living Room",
      sectionPhoto:
          "https://plus.unsplash.com/premium_photo-1675745330187-a6f001a21abe?q=80&w=2332&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ),
    PropertySection(
      sectionName: "Kitchen",
      sectionPhoto:
          "https://plus.unsplash.com/premium_photo-1678297270837-990c65fd1b64?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ),
    PropertySection(
      sectionName: "Swimming Pool",
      sectionPhoto:
          "https://plus.unsplash.com/premium_photo-1661962769148-fbe587e60fb8?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ),
    PropertySection(
      sectionName: "Bathroom",
      sectionPhoto:
          "https://plus.unsplash.com/premium_photo-1661962769148-fbe587e60fb8?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ),
    PropertySection(
      sectionName: "Dining Room",
      sectionPhoto:
          "https://plus.unsplash.com/premium_photo-1661962769148-fbe587e60fb8?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ),
    PropertySection(
      sectionName: "Garden",
      sectionPhoto:
          "https://plus.unsplash.com/premium_photo-1661962769148-fbe587e60fb8?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ),
    PropertySection(
      sectionName: "Garage",
      sectionPhoto:
          "https://plus.unsplash.com/premium_photo-1661962769148-fbe587e60fb8?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ),
    PropertySection(
      sectionName: "Balcony",
      sectionPhoto:
          "https://plus.unsplash.com/premium_photo-1661962769148-fbe587e60fb8?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ),
    PropertySection(
      sectionName: "Office",
      sectionPhoto:
          "https://plus.unsplash.com/premium_photo-1661962769148-fbe587e60fb8?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ),
    PropertySection(
      sectionName: "Hallway",
      sectionPhoto:
          "https://plus.unsplash.com/premium_photo-1661962769148-fbe587e60fb8?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ),
  ];
}
