name: cwt_ecommerce_admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.19.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.15
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  image_picker: ^1.1.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.2.6
  flutter_dropzone: ^3.0.7
  flutter_typeahead: ^5.2.0
  connectivity_plus: ^6.0.3
  flutter_rating_bar: ^4.0.1
  geolocator: ^13.0.2
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_charts: ^28.2.11
  loading_animation_widget: ^1.3.0
  table_calendar: ^3.1.3
  visibility_detector: ^0.4.0+2
  flutter_spinkit: ^5.2.1
  readmore: ^3.0.0
  dropdown_button2: ^2.3.9
  google_fonts: ^6.2.1


  # Web Specific
  web: ^1.0.0
  http: ^1.2.1
  fl_chart: ^0.67.0
  url_strategy: ^0.2.0
  data_table_2: ^2.5.12
  universal_html: ^2.2.4
  # Geolocator group
  geolocator_android: ^4.6.2
  geolocator_apple: ^2.3.13
  geolocator_web: ^4.1.3
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3

  #--------------- ./ PACKAGES END ------------------#

  uuid: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/icons/custom_icons/dark/
    - assets/icons/custom_icons/
    - assets/icons/custom_icons/nav_icons/
    - assets/icons/custom_icons/amenities/
    - assets/icons/custom_icons/light/
    - assets/icons/custom_icons/active/
    - assets/icons/custom_icons/inactive/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/icons/custom_icons/product_card/
    - assets/icons/custom_icons/icon_family/
    - assets/icons/custom_icons/header_nav_icons/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/static/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/static/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/static/Inter_18pt-Italic.ttf
          style: italic
        - asset: assets/fonts/inter/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/static/Inter_18pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/static/Inter_18pt-Bold.ttf
          weight: 800

    - family: Lora
      fonts:
        - asset: assets/fonts/lora/static/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/lora/static/Lora-Italic.ttf
          style: italic
        - asset: assets/fonts/lora/static/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/lora/static/Lora-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/lora/static/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/lora/static/Lora-Bold.ttf
          weight: 800

    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 800

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 800

    - family: CormorantGaramond
      fonts:
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-Light.ttf
          weight: 300
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-Italic.ttf
          style: italic
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-MediumItalic.ttf
          weight: 600
        - asset: assets/fonts/Cormorant_Garamond/static/CormorantGaramond-Bold.ttf
          weight: 800