import 'package:flutter/material.dart';
import '../../../../../utils/constants/enums.dart';
import '../../../../../utils/listing_data/listings_data.dart';
import '../../../../booking/models/booking/booking.dart';
import '../widgets/mobile/body.dart';

class ListingsMobileScreen extends StatelessWidget {
  const ListingsMobileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final bookings = [
      Booking(
          bookingId: '',
          bookieUserId: '',
          listerUserId: '',
          listing: TTestListings.properties[0],
          roomId: '',
          numberOfNights: 3,
          bookingStage: BookingStage.Availability,
          bookingNights: 3,
          bookingStart: DateTime.now(),
          bookingAmountTotal: 6700,
          bookingTaxFee: 0.12,
          bookingBookieFee: 670,
          bookingOrderTotal: 8700, checkInDate: DateTime.now(), checkOutDate: DateTime.now()),
      Booking(
          bookingId: '',
          bookieUserId: '',
          listerUserId: '',
          listing: TTestListings.properties[0],
          roomId: '',
          numberOfNights: 3,
          bookingStage: BookingStage.Availability,
          bookingNights: 3,
          bookingStart: DateTime.now(),
          bookingAmountTotal: 6700,
          bookingTaxFee: 0.12,
          bookingBookieFee: 670,
          bookingOrderTotal: 8700, checkInDate: DateTime.now(), checkOutDate: DateTime.now()),
      Booking(
          bookingId: '',
          bookieUserId: '',
          listerUserId: '',
          listing: TTestListings.properties[0],
          roomId: '',
          numberOfNights: 3,
          bookingStage: BookingStage.Availability,
          bookingNights: 3,
          bookingStart: DateTime.now(),
          bookingAmountTotal: 6700,
          bookingTaxFee: 0.12,
          bookingBookieFee: 670,
          bookingOrderTotal: 8700, checkInDate: DateTime.now(), checkOutDate: DateTime.now()),
      Booking(
          bookingId: '',
          bookieUserId: '',
          listerUserId: '',
          listing: TTestListings.properties[0],
          roomId: '',
          numberOfNights: 3,
          bookingStage: BookingStage.Availability,
          bookingNights: 3,
          bookingStart: DateTime.now(),
          bookingAmountTotal: 6700,
          bookingTaxFee: 0.12,
          bookingBookieFee: 670,
          bookingOrderTotal: 8700, checkInDate: DateTime.now(), checkOutDate: DateTime.now()),
      Booking(
          bookingId: '',
          bookieUserId: '',
          listerUserId: '',
          listing: TTestListings.properties[0],
          roomId: '',
          numberOfNights: 3,
          bookingStage: BookingStage.Availability,
          bookingNights: 3,
          bookingStart: DateTime.now(),
          bookingAmountTotal: 6700,
          bookingTaxFee: 0.12,
          bookingBookieFee: 670,
          bookingOrderTotal: 8700, checkInDate: DateTime.now(), checkOutDate: DateTime.now()),
      Booking(
          bookingId: '',
          bookieUserId: '',
          listerUserId: '',
          listing: TTestListings.properties[0],
          roomId: '',
          numberOfNights: 3,
          bookingStage: BookingStage.Availability,
          bookingNights: 3,
          bookingStart: DateTime.now(),
          bookingAmountTotal: 6700,
          bookingTaxFee: 0.12,
          bookingBookieFee: 670,
          bookingOrderTotal: 8700, checkInDate: DateTime.now(), checkOutDate: DateTime.now()),
      Booking(
          bookingId: '',
          bookieUserId: '',
          listerUserId: '',
          listing: TTestListings.properties[0],
          roomId: '',
          numberOfNights: 3,
          bookingStage: BookingStage.Availability,
          bookingNights: 3,
          bookingStart: DateTime.now(),
          bookingAmountTotal: 6700,
          bookingTaxFee: 0.12,
          bookingBookieFee: 670,
          bookingOrderTotal: 8700, checkInDate: DateTime.now(), checkOutDate: DateTime.now()),
      Booking(
          bookingId: '',
          bookieUserId: '',
          listerUserId: '',
          listing: TTestListings.properties[0],
          roomId: '',
          numberOfNights: 3,
          bookingStage: BookingStage.Availability,
          bookingNights: 3,
          bookingStart: DateTime.now(),
          bookingAmountTotal: 6700,
          bookingTaxFee: 0.12,
          bookingBookieFee: 670,
          bookingOrderTotal: 8700, checkInDate: DateTime.now(), checkOutDate: DateTime.now()),
      Booking(
          bookingId: '',
          bookieUserId: '',
          listerUserId: '',
          listing: TTestListings.properties[0],
          roomId: '',
          numberOfNights: 3,
          bookingStage: BookingStage.Availability,
          bookingNights: 3,
          bookingStart: DateTime.now(),
          bookingAmountTotal: 6700,
          bookingTaxFee: 0.12,
          bookingBookieFee: 670,
          bookingOrderTotal: 8700, checkInDate: DateTime.now(), checkOutDate: DateTime.now()),
      Booking(
          bookingId: '',
          bookieUserId: '',
          listerUserId: '',
          listing: TTestListings.properties[0],
          roomId: '',
          numberOfNights: 3,
          bookingStage: BookingStage.Availability,
          bookingNights: 3,
          bookingStart: DateTime.now(),
          bookingAmountTotal: 6700,
          bookingTaxFee: 0.12,
          bookingBookieFee: 670,
          bookingOrderTotal: 8700, checkInDate: DateTime.now(), checkOutDate: DateTime.now()),
      Booking(
          bookingId: '',
          bookieUserId: '',
          listerUserId: '',
          listing: TTestListings.properties[0],
          roomId: '',
          numberOfNights: 3,
          bookingStage: BookingStage.Availability,
          bookingNights: 3,
          bookingStart: DateTime.now(),
          bookingAmountTotal: 6700,
          bookingTaxFee: 0.12,
          bookingBookieFee: 670,
          bookingOrderTotal: 8700, checkInDate: DateTime.now(), checkOutDate: DateTime.now()),
      Booking(
          bookingId: '',
          bookieUserId: '',
          listerUserId: '',
          listing: TTestListings.properties[0],
          roomId: '',
          numberOfNights: 3,
          bookingStage: BookingStage.Availability,
          bookingNights: 3,
          bookingStart: DateTime.now(),
          bookingAmountTotal: 6700,
          bookingTaxFee: 0.12,
          bookingBookieFee: 670,
          bookingOrderTotal: 8700, checkInDate: DateTime.now(), checkOutDate: DateTime.now()),
    ];
    return Scaffold(
        body: ListingsBody(
          bookings: bookings,
        ));
  }
}
